query InputsVars ($first: Int!, $nextCursor: String) {
  allPeople (first: $first, after: $nextCursor) {  
    pageInfo {
      hasNextPage,
      hasPreviousPage,
      startCursor,
      endCursor
    },
    totalCount,
    people {
      id,
      name,
      height,
      mass,
      hairColor,
      skinColor,
      eyeColor,
      birthYear,
      gender,
      homeworld {
          name
      },
      created,
      edited
    }
  }
}
