query InputsVars ($first: Int, $last: Int, $after: String, $before: String) {
  allPeople (first: $first, last: $last, after: $after, before: $before) {  
    pageInfo {
      hasNextPage,
      hasPreviousPage,
      startCursor,
      endCursor
    },
    totalCount,
    people {
      id,
      name,
      height,
      mass,
      hairColor,
      skinColor,
      eyeColor,
      birthYear,
      gender,
      homeworld {
          name
      },
      created,
      edited
    }
  }
}
