{
  allPeople {
    people {
      name,
      height,
      mass,
      hairColor,
      skinColor,
      eyeColor,
      birthYear,
      gender,
      homeworld {
          name
      },
      created,
      edited
    }
  }
}
